spring:
    security:
        user:
            name: user
            password: 1111

    datasource:
        url: jdbc:mysql://localhost:3306/security
        username: root
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create
            format_sql: true
            show_sql: true
        open-in-view: false

    sql:
        init-mode: always
